### ISSUE TITLE
Loading error of 'debug' group in P9

### ISSUE THREAD

**Issue by tinchodias** [pharo-contributions/taskit#109]
1. Evaluate in a Pharo 9:
```
Metacello new
  baseline: 'TaskIt';
  repository: 'github://pharo-contributions/taskit';
  load: #(debug).
```
2. Get "Instance of PharoCommonTools did not understand #registerDebugger:withRank:".

Capture:

<img width="723" alt="Screen Shot 2021-05-19 at 15 01 44" src="https://user-images.githubusercontent.com/3044265/118869240-225b5600-b8b3-11eb-9bf8-682387099ea0.png">

**Comment by StevenCostiou** [comment]
We don't register debuggers manually anymore. Debuggers must implement the `TDebugger` trait to be recognized as debuggers by the system.
Here it is already the case, as `TKTDebugger` is a subclass of `GTDebugger`. 
If you look at the setting (screenshot)s, it is automatically recognized as a debugger, but it is deactivated.
I suggest the following configuration:
1. Set the debugger selection strategy to `OupsDebuggerSelector`. It was deactivated for a specific bug to see if it would happen again, but it works and is needed to apply a selection of debugger depending on the domain of the error.
2. Activate `TKTDebugger`.
3. Give it a higher priority (10 for instance). It must be the highest priority to be considered first before the Spec debugger that can handle any error.
4. Let me know how it works ;)

![Screenshot 2021-05-20 at 09 43 55](https://user-images.githubusercontent.com/26929529/118939498-09ed4900-b950-11eb-85c7-41b1a0e1850d.png)

**Comment by tinchodias** [comment]
Thank you very much, @StevenCostiou 

I think I applied correctly our suggestions in 2 commits in PR #110 
There is no error now, and with settings UI looking the same as in your capture.

But I think `TKTDebugger` is not taken into account by the system. I execute the example `TKTDebugger exampleFailure`.
And don't see anything special, plus I placed a `traceCr` in `TKTDebugger class>>#handlesContext:` and nothing is printed in transcript. Any clue?

<img width="519" alt="Screen Shot 2021-05-20 at 13 39 12" src="https://user-images.githubusercontent.com/3044265/119024156-c6ef9d80-b970-11eb-8a90-5b9c9a943a97.png">

(I have to warn that I'm a kind of late maintainer of the project, I'm really not sure how show it work correctly this package... but I think something should appear in the debugger when the example is executed).


Additional question:

`TKTDebugger` provides enable/disable/isEnabled protocol in class side, which stores a boolean in a class variable... I 
added a check for this variable in `TKTDebugger class>>#handlesContext:`. However, as I see this "Available" checkbox in the settings, I suppose this "enabled" management is redundant and there is an general way to tell the system that TKTDebugger is available programmatically, and remove the custom enabled. Do you know?

**Comment by StevenCostiou** [comment]
> Thank you very much, @StevenCostiou
> 
> I think I applied correctly our suggestions in 2 commits in PR #110
> There is no error now, and with settings UI looking the same as in your capture.
> 
> But I think `TKTDebugger` is not taken into account by the system. I execute the example `TKTDebugger exampleFailure`.
> And don't see anything special, plus I placed a `traceCr` in `TKTDebugger class>>#handlesContext:` and nothing is printed in transcript. Any clue?

Could you put the `StDebugger` to priority 9 (in any case lower than TKT) and try again?
This is how GT used to work, the generic debugger was at a lower priority so that all specialized debuggers with a higher priority had a chance to capture a domain exception and open instead.


> `TKTDebugger` provides enable/disable/isEnabled protocol in class side, which stores a boolean in a class variable... I
> added a check for this variable in `TKTDebugger class>>#handlesContext:`. However, as I see this "Available" checkbox in the settings, I suppose this "enabled" management is redundant and there is an general way to tell the system that TKTDebugger is available programmatically, and remove the custom enabled. Do you know?

The correct enabled configuration is the one in the settings, which is obtained through the `TDebugger` trait.
What happens when a client in the system asks for a debugger opening (an exception or a debug it, etc.) is that the debugger system gathers all classes using the `TDebugger` trait and selects from them all enabled debuggers (*i.e.*, enabled in the settings) that can handle the exception context (*i.e*, `handlesContext:` returns `true`).

For more details, you could check the paper in which we described the mechanism (there is 2 drawings explaining simply) : https://hal.inria.fr/hal-02992644/document

To answer your question, in `handlesContext:` there should not be any check for knowing if the debugger is enabled, except if that is part of your logic of handling the context. If it goes through `handlesContext:`, then the debugger **is** enabled.

**Comment by tinchodias** [comment]
Thanks @StevenCostiou. Yes, as you suggested, it was necessary to set priority 9 to the StDebugger (and keep TKTDebugger at 10).

**Comment by tinchodias** [comment]
I also had to change this setting to "development":

<img width="479" alt="Screen Shot 2021-05-20 at 16 07 36" src="https://user-images.githubusercontent.com/3044265/119054959-7c811780-b996-11eb-8409-95c1e916c054.png">

However, to fix this issue, I'd need more understanding of the TaskItDebugger... I see that a TaskIt debugger opened but I don't get what's the difference with the normal debugger.

**Comment by tinchodias** [comment]
Update: this issue is specifically about the loading error in P9, so I will close it, but open another one.
