### ISSUE TITLE
Move taskit to pharo-contributions

### ISSUE THREAD

**Issue by noha** [pharo-contributions/taskit#70]
TaskIt is super cool ;) and is used more widely. I propose to move to pharo-contributions to make it better manageable

**Comment by sbragagnolo** [comment]
I was thinking what if we have a pharo-process? I would like to ensure that whatever person goes to check some processing thing knows all the available related thing.  Asking from ignorance, maybe there is a wonderful way to do it out of this. But in general I completely agree. I have been thinking on this kind of movement since some time already.

**Comment by noha** [comment]
I‘m up to discussing a process. Usually I wait until there is a problem but why not. There is plenty of possibilities but we should discuss this on the mailing list, no?

**Comment by sbragagnolo** [comment]
Super. I'll send mail tomorrow then!

**Comment by tinchodias** [comment]
this is already done
